{
 "title": "GSP Imports",
 "description": "Import GSP metrics",
 "tags": [
  "test",
  "metrics",
  "traces"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GSP Imports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "B2B_app_ImportGspProcessor_handleImportSingle_calls_total",
     "legendFormat": "GSP Events"
    },
    {
     "expr": "B2B_app_ImportGspParticipantsProcessor_countBatchCall_calls_total",
     "legendFormat": "GSP Participants"
    }
   ]
  },
  {
   "title": "GSP Import rates",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(B2B_app_ImportGspProcessor_handleImportSingle_calls_total[$__rate_interval])",
     "legendFormat": "GSP Event rate"
    },
    {
     "expr": "rate(B2B_app_ImportGspParticipantsProcessor_countBatchCall_calls_total[$__rate_interval])",
     "legendFormat": "GSP Participant rate"
    }
   ]
  },
  {
   "title": "B2B_system_cpu_time/utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "B2B_system_cpu_utilization", "legendFormat": "CPU utilization" },
    {
     "expr": "rate(B2B_system_cpu_time[$__rate_interval])",
     "legendFormat": "CPU time"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "B2B_system_memory_usage/utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "B2B_system_memory_utilization", "legendFormat": "mem utilization" },
    { "expr": "B2B_system_memory_usage", "legendFormat": "mem usage" }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(B2B_system_network_io[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "B2B_http_request_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(B2B_http_request_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}