{
 "title": "hello world",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "trace hello",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "operation": "GET /hello", "service": "observable_app" }
   ]
  },
  {
   "title": "trace world",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "operation": "GET /world", "service": "observable_app" }
   ]
  },
  {
   "title": "hello world",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "B2B_app_AppService_getHello_calls_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "B2B_app_AppService_getWorld_calls_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory useage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "expr": "B2B_system_memory_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "B2B_system_memory_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "B2B_system_cpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    { "expr": "B2B_system_cpu_time", "legendFormat": "__auto" }
   ]
  }
 ]
}